spring.datasource.url=jdbc:postgresql://localhost:5433/school_manager_db
spring.datasource.username=postgres
spring.datasource.password=1106
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jackson.time-zone=America/Sao_Paulo

application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000

server.port=8080
server.error.include-message=always

# Logging
logging.level.com.project.school_manager=DEBUG
logging.level.org.springframework.security=DEBUG