spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jackson.time-zone=America/Sao_Paulo

application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=86400000

server.port=8080
server.error.include-message=always

logging.level.com.project.school_manager=DEBUG
logging.level.org.springframework.security=DEBUG